services:
  app:
    build:
      context: .
      target: app
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - ./.env:/var/www/.env:ro
      - storage-data:/var/www/storage

volumes:
  storage-data:
