services:
  # 后端 API 服务
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cloud_gallery_app
    restart: always
    working_dir: /var/www
    # 内部端口 8000，不再直接暴露给公网 (通过 frontend 代理)
    # 如果需要调试，可以映射 8000:8000
    expose:
      - "8000"
    volumes:
      - ./:/var/www
      - app_vendor:/var/www/vendor
    networks:
      - cloud-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306

  # 前端 Web 服务 (Nginx)
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: cloud_gallery_frontend
    restart: always
    ports:
      - "8000:80" # 宿主机 8000 -> 容器 80
    networks:
      - cloud-network
    depends_on:
      - app

  # MySQL 数据库服务

  mysql:
    image: mysql:8.0
    container_name: cloud_gallery_db
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      # MYSQL_USER 和 MYSQL_PASSWORD 用于创建非 root 用户，如果 DB_USERNAME 是 root 则会报错
      # 这里只保留 ROOT 密码即可
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge

volumes:
  db_data: